services:
  - type: web
    name: asinhhccp8-hos-api
    runtime: docker
    dockerfilePath: ./hos/deploy/Dockerfile
    healthCheckPath: /health
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
